### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tobiasvonarx** [tobiasvonarx/HTML5-JS#2]
### TODO

- [ ] Global multiplayer in Tic Tac Toe
- [ ] Global multiplayer in racing game
- [ ] Lint everything & rewrite using es6
- [ ] Unittests with circleci to ensure stylistically correct code (in combination with linter)
- [ ] Tensorflow.js with the neuroevolution racing game
- [x] Music vs. microphone audio sampler and grapher w/ chartjs
- [ ] Voronoi diagrams
